


spring:
  profiles:
    active: dev









---
spring:
  config:
    activate:
      on-profile: dev


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/todo_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message:
    config: Hello World

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"





---
spring:
  config:
    activate:
      on-profile: qa


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/todo_app_qa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message:
    config: Hello World


---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/todo_app_prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message:
    config: Hello World

